---
cloud_controller_uri: api.vcap.me
service:
  name: cassandra
  version: "1.0"
  description: 'Cassandra service'
  plans: ['free']
  default_plan: free
  tags: ['cassandra', 'cassandra-1.0', 'cassandrabased', 'demo']
ip_route: localhost
index: 0
token: changecassandratoken
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/cassandra_service.pid
node_timeout: 2
