---
plan: free
capacity: 100
local_db: sqlite3:/var/vcap/services/cassandra/cassandra_node.db
mbus: nats://localhost:4222
base_dir: /var/vcap/services/cassandra/
index: 0
logging:
  level: debug
pid: /var/vcap/sys/run/cassandra_node.pid
node_id: cassandra_node_1
port: 5002
supported_versions: ["1.0"]
